version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: us-east-2
    AWS_ACCOUNT_ID: 789530852735
    IMAGE_TAG: latest
    IMAGE_REPO_NAME: firstregister
phases:
  install:
    runtime-versions:
      java: openjdk8
      docker: 18
    commands:
      - echo Entered the install phase
      - apt-get update -y
  
  pre_build:
    commands:
      - echo logging in to AWS ECR
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION) 
      #docker login -u devopsuser -p infosys@123 https://$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
  
  build:
    commands:
      - echo Entered the build phase
      - echo Build started on `date`
      - mvn install
      - echo Building the Docker image
      - echo Build started on `date`
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  
  post_build:
    commands:
      - echo Entered the post_build phase
      - echo Build completed on `date`
      - echo Pushing the Docker image
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
artifacts:
  files:
    - target/my-app-1.0-SNAPSHOT.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
